### ISSUE TITLE
Practicum 5 Country tabel is vol met undefineds

### ISSUE THREAD

**Issue by graddus** [EduardGarritsen/TICT-V1WAC-15#1]
Dit komt doordat de restservice bij /countries alleen de name doorgeeft.
Ook gebruik je bij loadCountries een eventlistener die object.latitude en object.longitude meegeeft, terwijl de namen van deze attributen (gebaseerd op je /countries/id) lat en lng heten.

**Comment by Josvanreenen** [comment]
fixed
